export const keys = [
  { id: 1, key: 7 },
  { id: 2, key: 8 },
  { id: 3, key: 9 },
  { id: 4, key: "DEL" },
  { id: 5, key: 4 },
  { id: 6, key: 5 },
  { id: 7, key: 6 },
  { id: 8, key: "+" },
  { id: 9, key: 1 },
  { id: 10, key: 2 },
  { id: 11, key: 3 },
  { id: 12, key: "-" },
  { id: 13, key: "." },
  { id: 14, key: 0 },
  { id: 15, key: "/" },
  { id: 16, key: "x" },
  { id: 17, key: "RESET" },
  { id: 18, key: "=" },
];
